import AppShell from '@/components/layout/app-shell'
import LegalPage from '@/components/pages/legal-page'

export const metadata = {
  title: 'Privacy Policy — VibeWave',
}

export default function Page() {
  return (
    <AppShell>
      <LegalPage
        title="Privacy Policy"
        lastUpdated="April 1, 2025"
        sections={[
          {
            id: 'overview',
            heading: '1. Overview',
            body: 'VibeWave ("we," "us," or "our") is committed to protecting your privacy. This Privacy Policy describes how we collect, use, and share information about you when you use our services. By using VibeWave, you agree to the collection and use of information in accordance with this policy.',
          },
          {
            id: 'collection',
            heading: '2. Information We Collect',
            body: 'We collect information you provide directly (such as name, email, and payment details), information generated by your use of the Service (such as listening history, search queries, and device information), and information from third parties (such as social login providers when applicable). We do not sell your personal data to third parties.',
          },
          {
            id: 'use',
            heading: '3. How We Use Your Information',
            body: 'We use your information to provide, maintain, and improve the Service; personalize your music experience through our AI engine; process transactions and send related notices; send communications including updates and promotional materials (which you may opt out of); and comply with legal obligations.',
          },
          {
            id: 'ai',
            heading: '4. AI Personalization',
            body: 'Our AI analyzes listening patterns, skip behavior, and session context to generate personalized mixes and recommendations. This processing happens on VibeWave\'s infrastructure and your data is not shared with external AI providers for training purposes. You may opt out of AI personalization in Settings > Privacy.',
          },
          {
            id: 'sharing',
            heading: '5. Information Sharing',
            body: 'We do not sell, trade, or rent your personal information to third parties. We may share information with service providers who assist us in operating the Service under strict confidentiality agreements, and when required by law or to protect our rights.',
          },
          {
            id: 'cookies',
            heading: '6. Cookies and Tracking',
            body: 'We use cookies and similar tracking technologies to operate the Service, remember your preferences, and analyze usage patterns. You can control cookies through your browser settings, though disabling them may affect Service functionality.',
          },
          {
            id: 'retention',
            heading: '7. Data Retention',
            body: 'We retain personal data for as long as your account is active or as needed to provide the Service. Upon account deletion, we will delete your data within 30 days except where we are required to retain it by law.',
          },
          {
            id: 'rights',
            heading: '8. Your Rights',
            body: 'Depending on your jurisdiction, you may have the right to access, correct, or delete your personal data; object to or restrict processing; and data portability. To exercise these rights, contact privacy@vibewave.fm or use the data controls in Profile > Settings > Privacy.',
          },
          {
            id: 'security',
            heading: '9. Security',
            body: 'We implement industry-standard security measures including encryption in transit (TLS) and at rest. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.',
          },
          {
            id: 'contact-privacy',
            heading: '10. Contact',
            body: 'For privacy-related inquiries, contact our Data Protection Officer at privacy@vibewave.fm or write to VibeWave Inc., 123 Mission Street, San Francisco, CA 94105.',
          },
        ]}
      />
    </AppShell>
  )
}
